# cc_binary(
#     name = "accumulators_test",
#     srcs = ["accumulators_test.cpp"],
#     deps = [
#         "@com_github_boost_accumulators//:accumulators",
#     ]
# )

cc_binary(
    name = "algorithm_test",
    srcs = ["algorithm_test.cpp"],
    deps = [
        "@com_github_boost_algorithm//:algorithm",
    ]
)

cc_binary(
    name = "crc_test",
    srcs = ["crc_test.cpp"],
    deps = [
        "@com_github_boost_crc//:crc",
    ]
)
